# Generated by Django 3.1.5 on 2021-01-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(max_length=1024),
        ),
    ]
