# Generated by Django 3.1.5 on 2021-03-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210127_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'ServicesCatalog'},
        ),
    ]
